name: Export Garmin Activities

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Restore Garmin tokens
        run: |
          mkdir -p ~/.garminconnect
          echo "${{ secrets.GARMIN_OAUTH1 }}" > ~/.garminconnect/oauth1_token.json
          echo "${{ secrets.GARMIN_OAUTH2 }}" > ~/.garminconnect/oauth2_token.json

      - name: Install dependencies
        run: pip install garminconnect httpx cloudscraper

      - name: Run Garmin exporter
        run: |
          python running/garminconnect_exporter.py \
            --username "${{ secrets.GARMIN_USERNAME }}" \
            --password "${{ secrets.GARMIN_PASSWORD }}"

      - name: Commit updated CSV
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/components/activities.csv
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update activities.csv"
            git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}.git
            git push
          fi
